a=float(input("Enter First Number: "))
b=float(input("Enter Second Number: "))
print("Addition is: ",a+b)
print("Subtraction is: ",a-b)
print("Multiple is: ",a*b)
print("Division is: ",a/b)
print("Remainder is: ",a%b)
print("Floor value is: ",a//b)
print("First to the power of second is: ",a**b)
